### ISSUE TITLE
Unkown data type on 1909

### ISSUE THREAD

**Issue by aberencsi** [AntonSikidin/elitechat#1]

**Comment by aberencsi** [comment]
Hi Anton,

first congratulations on this very creative work. 

I tried to pull on that system:
SLT	2.0	SP16 (01/2019)	sap.com	SAP LT REPLICATION SERVER 2.0
ABAP PLATFORM	1909	02 (04/2020)	sap.com	ABAP PLATFORM 1909
SAP S/4HANA FOUNDATION	1909	02 (05/2020) FP	sap.com	SAP S/4HANA FOUNDATION 1909
SAP FIORI FRONT-END SERVER	6.0	Initial Shipment Stack	sap.com	SAP FIORI FRONT-END SERVER 6.0

but some errors occured, due unkown data types.

Field DATES: Component type or domain used not active or does not exist
Could not determine structure width of ZHAT_ST_HISTORY
Nametab for table ZHAT_ST_HISTORY cannot be generated
Row type ZHAT_ST_HISTORY is not active or does not exist
Field HISTORY: Table type ZHAT_TT_HISTORY is not active or does not exist
Table ZCHAT_ST_RESPONCE could not be activated
Table ZHAT_ST_HISTORY could not be activated
Table Type ZHAT_TT_HISTORY could not be activated
Return code..............: 8


Would it be possible to replace that component with a custom Z types for compatibility reasons ? 

Thank you very much
Greetings,Attila

**Comment by AntonSikidin** [comment]
thank you for respond. I will fix it and notify you

чт, 20 трав. 2021, 22:45 користувач aberencsi ***@***.***>
пише:
